// 技能中文展示名（本地补丁 · 2026-09-17）
// 展示层：中文名给用户看（大字）；skill id 原名保持小字，供 agent / 排查使用。
// 数据源：能力清单菜单（capability-menu），重新生成即可更新。
export const SKILL_DISPLAY_NAMES: Record<string, string> = {
  'ai-image-gen': 'AI 生图',
  'ai-music': 'BGM / 音乐生成',
  'ai-video-gen': 'AI 视频生成',
  'asset-manager': '产物管理',
  'audio-denoise': '降噪',
  'audio-editing': '音频剪辑',
  'audio-mix': '混音（BGM闪避）',
  'audio-visualizer': '音频可视化',
  'auto-short-video': '一句话出片',
  'auto-subtitle': '自动字幕',
  'batch-process': '批量处理',
  'beat-sync-video': '卡点视频',
  'card-design': '卡片视觉系统',
  'card-quote': '金句卡 / 数据卡',
  'card-xiaohongshu': '小红书卡组',
  'chart-visualization': '图表（25+类）',
  'clipify': '长片切片',
  'comparison-card': '对比图 / 一图流',
  'copywriting': '营销 / 带货文案',
  'data-report': '数据报告页',
  'doc-convert': '文稿转 PDF / 长图',
  'ecom-details-image': '电商详情图',
  'green-screen': '绿幕合成',
  'gzh-design': '公众号排版',
  'image-editing': '图像处理',
  'image-enhance': '图像增强',
  'infographic': '信息图（含GIF）',
  'meme-generator': '表情包',
  'mindmap': '思维导图',
  'multi-voice-dubbing': '多角色配音',
  'novel-writer': '小说连载',
  'paper-explainer': '论文解读',
  'post-formatter': '社媒帖子成稿',
  'poster-hero': '竖版海报',
  'remove-bg': '抠图换背景',
  'roi-calculator': 'ROI 计算',
  'short-drama': 'AI 微短剧',
  'skill-account-diagnosis': '账号诊断',
  'skill-algorithm-updates': '算法规则追踪',
  'skill-article-outline': '长文大纲',
  'skill-audience-profiler': '受众画像',
  'skill-bilibili-upload': 'B站',
  'skill-brand-onboarding': '品牌入驻访谈',
  'skill-campaign-planner': '活动策划',
  'skill-carousel-planner': '轮播规划',
  'skill-channels-upload': '微信视频号',
  'skill-collab-proposal': '品牌合作',
  'skill-comment-insights': '评论洞察',
  'skill-community-ops': '评论运营',
  'skill-competitor-analysis': '竞品分析',
  'skill-content-calendar': '月度排期',
  'skill-content-calendar-log': '内容日历底座',
  'skill-content-gap-analysis': '内容空白分析',
  'skill-content-matrix': '选题矩阵',
  'skill-content-postmortem': '爆款复盘',
  'skill-content-repurposing': '多平台改编',
  'skill-content-strategy': '内容策略',
  'skill-cross-platform-diff': '跨平台差异',
  'skill-cross-platform-publish': '跨平台一键',
  'skill-data-tracker': '数据追踪',
  'skill-douyin-upload': '抖音',
  'skill-event-calendar': '节日 / 节点',
  'skill-hook-generator': '开头钩子',
  'skill-kuaishou-upload': '快手',
  'skill-livestream': '直播方案',
  'skill-my-account': '账号查询',
  'skill-news-intelligence': '行业情报',
  'skill-persona-check': '人设一致性',
  'skill-positioning-analysis': '差异化定位',
  'skill-post-scorer': '互动潜力评分',
  'skill-profile-builder': '画像构建',
  'skill-profile-manager': '画像管理',
  'skill-publish-analytics': '发布归因',
  'skill-publish-checklist': '发布前检查',
  'skill-publish-log': '发布记录',
  'skill-publish-notify': '发布通知',
  'skill-publish-scheduler': '批量排期',
  'skill-quality-gate': '质量关',
  'skill-risk-scanner': '版权 / 原创风险',
  'skill-rss-aggregator': 'RSS 订阅',
  'skill-seo-quality': '搜索流量优化',
  'skill-short-link': '短链 / UTM',
  'skill-social-performance-review': '月度复盘',
  'skill-strategy-advisor': '策略迭代',
  'skill-topic-evaluator': '选题评估',
  'skill-trend-rider': '蹭热点方案',
  'skill-trending-topics': '热榜选题',
  'skill-ugc-discovery': '粉丝 UGC',
  'skill-voice-builder': '声音画像',
  'skill-wechat-publisher': '公众号',
  'skill-xhs-analyzer': '小红书分析',
  'skill-xhs-comment-reply': '小红书评论',
  'skill-xhs-publisher': '小红书',
  'skill-zhihu-answer': '知乎回答',
  'skill-zhihu-publisher': '知乎专栏',
  'slideshow-video': '相册视频',
  'social-content': '通用社媒文案',
  'style-transfer': '文案风格迁移',
  'subtitle-translate': '字幕翻译',
  'template-library': '模板库',
  'text-condenser': '摘要 / 金句提取',
  'text-polisher': '润色 / 去AI味',
  'tts-voiceover': '配音（带字幕）',
  'video-chapters': '章节 / 时间戳',
  'video-editing': '自然语言剪辑',
  'video-highlights': '高光切片',
  'video-intro-outro': '片头 / 片尾',
  'video-reframe': '画幅转换',
  'video-script': '视频脚本',
  'video-strategy': '视频策略选型',
  'video-to-article': '视频转图文',
  'voice-clone': '声音克隆',
  'xhs-note-creator': '小红书图文总入口',
};

export function displayName(raw: string): string {
  return SKILL_DISPLAY_NAMES[raw] || raw;
}
